version: "3"
tasks:
  # CLI
  build:
    desc: Build the project in release mode (native Apple Silicon)
    cmds:
      - cargo build --release
    sources:
      - src/**/*.rs
      - Cargo.toml
    generates:
      - target/release/git-ai-cli
  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean
  release:local:
    desc: Build release and install to user bin directory
    deps: [build]
    cmds:
      - cp target/release/git-ai ~/.local/bin/git-ai
      - chmod +x ~/.local/bin/git-ai

  # Extensions
  cursor:build:
    desc: Build the cursor extension
    dir: agent-support/cursor
    cmds:
      - yarn install
      - yarn run compile
  cursor:publish:
    desc: publish the cursor extension
    deps: [cursor:build]
    dir: agent-support/cursor
    cmds:
      - npx vsce package --out cursor-git-ai.vsix
      - npx ovsx publish cursor-git-ai.vsix
